# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference
# Keep PHP 8.1 for the minimum compatibility requirement

version: 2
updates:

  - package-ecosystem: "github-actions"
    target-branch: "main"
    directory: "/.github/workflows/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]

  - package-ecosystem: "docker"
    target-branch: "main"
    directory: "/.docker/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "serversideup/php"

  - package-ecosystem: "docker-compose"
    target-branch: "main"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]

  - package-ecosystem: "composer"
    target-branch: "main"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]
